- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Import Vpc Variables
    include_vars: vars/vpc_setup

  - name: create a VPC with dedicated tenancy and a couple of tags
    amazon.aws.ec2_vpc_net:
      name: "{{vpc_name}}"
      cidr_block: "{{vpcCidr}}"
      region: "{{region}}"
      dns_support: yes
      dns_hostnames: yes
      tenancy: dedicated
      tags:
        module: ec2_vpc_net
        this: works      
      state: "{{state}}"
    register: vpcout
